### ISSUE TITLE
Questions regarding easy-routes+errors 

### ISSUE THREAD

**Issue by kilianmh** [mmontone/easy-routes#13]
Two questions:
- Should the class `easy-routes-errors-acceptor` in https://github.com/mmontone/easy-routes/blob/80334a74f4ff176c79a6dedec46316b138016af7/errors.lisp#L3 also have `easy-routes-acceptor` as superclass? Else `easy-routes-errors-acceptor` does not not work (at least for me).
- Is there a specific reason why you made an extra system for `easy-routes+errors` instead of including it in`easy-routes`? The error messages are quite helpful, especially during development! We can simply add the classes `easy-routes-errors-acceptor`,`easy-routes-ssl-acceptor`, `routes-errors-acceptor` and export symbols so the users can decide if/when they use it.

**Comment by mmontone** [comment]
I suspect that is part of a refactoring I made where I implemented error handling for easy-routes and then I thought it was a more generic thing, as error handling does not have to do with routing and can and maybe should be provided as a separate thing and can be used independently of easy-routes.

Now that I look I think you are right easy-routes-acceptor should be a superclass, and I'm not against the helper classes. But I think it is better to maintain hunchentoot-errors as a separate library. I made easy-routes+errors a separate system because it adds a dependency the user may not need (hunchentoot-errors) when using easy-routes.

**Comment by kilianmh** [comment]
Oh I misread your last comment. Should I close the PR #15 and we spin off the library `easy-routes+errors` maybe as `easy-routes-plus-errors` (like cl-plust-ssl) into a separately maintained project?

**Comment by mmontone** [comment]
No, no. I mean keep hunchentoot-errors as separate library. But have only
one easy-routes project, with potentially several asdf systems, one for the
errors integration.

**Comment by mmontone** [comment]
I changed my mind about the error helper classes. I prefer not to have them. So I'm not mergin your pull request. Apologies.

**Comment by kilianmh** [comment]
All good. Thanks for this library ;)
